-- http://projecteuler.net/index.php?section=problems&id=2

-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

-- Find the sum of all the even-valued terms in the sequence which do not exceed four million.


-- the even numbers from the Fibonacci sequence can be determined via this formulae
-- [ ..., k, m, 4 * m + k, 4 * (4 * m + k) + m, ...
-- E(n) = 4 * E(n-1) + E(n-2)


-- naive solution
-- call:
-- 2 + 8 + euler_p002 2 8
euler_p002 k m = let p = 4 * m + k
                 in if p < 4000000
                    then p + euler_p002 m p
                    else 0